// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZDRAXkUsoA_pT5owK6JkkRTI9OabyajE',
    appId: '1:774960596419:web:833cc3c8d0d9a88700e976',
    messagingSenderId: '774960596419',
    projectId: 'product-test-555c2',
    authDomain: 'product-test-555c2.firebaseapp.com',
    databaseURL: 'https://product-test-555c2-default-rtdb.firebaseio.com',
    storageBucket: 'product-test-555c2.appspot.com',
    measurementId: 'G-969RX92WX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApBHQF9iALlBAgvDmR8O3PMzFeUZtfPB0',
    appId: '1:774960596419:android:b1e71b0dcd814e2c00e976',
    messagingSenderId: '774960596419',
    projectId: 'product-test-555c2',
    databaseURL: 'https://product-test-555c2-default-rtdb.firebaseio.com',
    storageBucket: 'product-test-555c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNEJCrruuUrPy5_JIwhN8FufqA7NMUvJQ',
    appId: '1:774960596419:ios:db5e4686dc23288f00e976',
    messagingSenderId: '774960596419',
    projectId: 'product-test-555c2',
    databaseURL: 'https://product-test-555c2-default-rtdb.firebaseio.com',
    storageBucket: 'product-test-555c2.appspot.com',
    iosBundleId: 'com.example.loginBf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNEJCrruuUrPy5_JIwhN8FufqA7NMUvJQ',
    appId: '1:774960596419:ios:b7b49e79848a00e200e976',
    messagingSenderId: '774960596419',
    projectId: 'product-test-555c2',
    databaseURL: 'https://product-test-555c2-default-rtdb.firebaseio.com',
    storageBucket: 'product-test-555c2.appspot.com',
    iosBundleId: 'com.example.loginBf.RunnerTests',
  );
}
